# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.array_ops_api import ArrayOpsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestArrayOpsApi(unittest.TestCase):
    """ArrayOpsApi unit test stubs"""

    def setUp(self):
        self.api = ArrayOpsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_max_array(self):
        """Test case for max_array

        """
        pass

    def test_min_array(self):
        """Test case for min_array

        """
        pass

    def test_multiply_arrays(self):
        """Test case for multiply_arrays

        """
        pass

    def test_sort_array(self):
        """Test case for sort_array

        """
        pass

    def test_sum_arrays(self):
        """Test case for sum_arrays

        """
        pass


if __name__ == '__main__':
    unittest.main()
