/*
 * This source file was generated by the Gradle 'init' task
 */
package xs.arraycalc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ProviderTest {
    @Test void appHasAGreeting() {
        Provider classUnderTest = new Provider();
    }
}
