/*
 * This source file was generated by the Gradle 'init' task
 */
package xs.arraycalc;

import javax.xml.ws.Endpoint;

public class Provider {
    private static final String URL = "http://localhost:9000/arrayops";

    public static void main(String[] args) {

        ArrayOps arrayops = new ArrayOps();
        System.out.println("Publishing ArrayOps Service");
        Endpoint.publish(URL, arrayops);
        System.out.println("ArrayOps Service Published");
    }
}
